### PR TITLE
navbar height not detected correctly

### PR DESCRIPTION
**Pull request by steinerjakob**
Fixes the second problem of issue #3

### CODE REVIEW

**Comment by EddyVerbruggen** [comment]
Hi! I can't reproduce it on my devices, but I don't have the Huawei P10 so what I did was regression-test on my devices with your changes and everything still works as before so I'll go ahead and merge your changes.

THANKS!

**Comment by EddyVerbruggen** [comment]
After more testing I found that this breaks the toolbar on Samsung Galaxy S8 in case the navigation bar at the bottom is hidden. When the keyboard pops up, the navbar is show, the keyboard above that, and the toolbar should be above the keyboard. But because it doesn't expect the navbar, the toolbar is too low (behind the keyboard).

I guess opening the keyboard on the P10 doesn't also show the navbar?

**Comment by steinerjakob** [comment]
No opening the keyboard doesn't show the navbar on the P10.
It's a pitty that each oem has different implementations...
Maybe a little delay after the keyboard open event would help, so the code can determine the visible navbar?
|photo_2019-01-31_12-54-53|photo_2019-01-31_12-55-00|

**Comment by EddyVerbruggen** [comment]
Hey @stoanarrr I was actually trying that but that didn't work. Looking into it some more.

Thanks for sharing those screenshots - indeed the behavior is quite different.

**Comment by EddyVerbruggen** [comment]
I'll release a new version soon (an hour) - would be great if you can give it a spin on your P10.

**Comment by steinerjakob** [comment]
Yeah sure, going to try it out in the evening ;)

**Comment by EddyVerbruggen** [comment]
1.0.3 is on npm. It fixes the problem for devices with a hidden navbar that pops up when the keyboard is shown (S8). Hopefully it also (still) fixes the issue for devices with a hidden navbar that keeps it hidden when the keyboard is open (P10).

**Comment by steinerjakob** [comment]
Didn't work for my P10, previous problem appeared (space between toolbar and keyboard)
I tried some things and came up with #5 -> solved for me the problem again (Hopefully for you to).

**Comment by EddyVerbruggen** [comment]
Hey, that's interesting! I'll test that :)

**Pull request merged**
